name: matcher
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - aioredis=2.0.1
  - asyncpg=0.28.0
  - pyscipopt=4.3.0
  - redis=3.5.3
  - typeguard=4.1.3
  - ordered_enum=0.0.8
  - pip:
      - aiogram==2.25.1
      - psycopg2==2.9.7
